### ISSUE TITLE
Issue running locally.

### ISSUE THREAD

**Issue by peterluu** [yahoo/pure-site#357]
So, I don't know what I'm doing wrong.

Below is a copy of the error log (npm-debug.log)

````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@4.1.2
3 info using node@v6.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pure-site@1.18.13~prestart: pure-site@1.18.13
6 silly lifecycle pure-site@1.18.13~prestart: no script for prestart, continuing
7 info lifecycle pure-site@1.18.13~start: pure-site@1.18.13
8 verbose lifecycle pure-site@1.18.13~start: unsafe-perm in lifecycle true
9 verbose lifecycle pure-site@1.18.13~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Peter/Github/pure-site/node_modules/.bin:/Users/Peter/.rvm/gems/ruby-2.4.0-rc1/bin:/Users/Peter/.rvm/gems/ruby-2.4.0-rc1@global/bin:/Users/Peter/.rvm/rubies/ruby-2.4.0-rc1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Peter/.rvm/bin
10 verbose lifecycle pure-site@1.18.13~start: CWD: /Users/Peter/Github/pure-site
11 silly lifecycle pure-site@1.18.13~start: Args: [ '-c', 'node server.js' ]
12 silly lifecycle pure-site@1.18.13~start: Returned: code: 1  signal: null
13 info lifecycle pure-site@1.18.13~start: Failed to exec start script
14 verbose stack Error: pure-site@1.18.13 start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid pure-site@1.18.13
16 verbose cwd /Users/Peter/Github/pure-site
17 error Darwin 16.0.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.9.4
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error pure-site@1.18.13 start: `node server.js`
22 error Exit status 1
23 error Failed at the pure-site@1.18.13 start script 'node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the pure-site package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs pure-site
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls pure-site
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
````

Any ideas?

**Comment by redonkulus** [comment]
I just ran this locally and it worked fine for me. Here are the versions of node and npm that i'm using locally:

```
$ npm -v
3.10.3
$ node -v
v6.3.1
```

**Comment by LeoMingo** [comment]
Indeed, I ran apt-get install npm and the latest version it gave me was 1.4.2, and I had not installed node.js, so I installed node.js and npm's version became up-to-date, problem solved.

**Comment by redonkulus** [comment]
Ok glad it worked. I usually use nvm to manage the versions of node or npm that are installed. 

@peterluu please let me know if the same steps help.
